development:
  adapter: postgresql
  encoding: unicode
  database: ofton_rails_development
  pool: 5
  username: oftonrails
  password:
  host: localhost
  url: postgresql://localhost/ofton_rails_development?pool=5

test:
  adapter: postgresql
  encoding: unicode
  database: ofton_rails_test
  pooL: 5
  username: oftonrails
  password:
  host: localhost

